### PR TITLE
cs lang correction by updated general

### PR DESCRIPTION
**Pull request by LordJazzus**
Here is it :)

### CODE REVIEW

**Comment by brezedc** [comment]
Awesome, thank you!
Just added on more minor thing on twitter, please translate it as well.

**Comment by LordJazzus** [comment]
@brezedc added

**Comment by LordJazzus** [comment]
Date of merge ? I i must do change only local. Thanks

**Comment by LordJazzus** [comment]
?

**Comment by brezedc** [comment]
There's a new update for the locales, please update it :D!

**Comment by LordJazzus** [comment]
Last chance :KEKW:

**Comment by LordJazzus** [comment]
Done

**Pull request merged**
