### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by DARKAOFF**

### CODE REVIEW

**Comment by brezedc** [comment]
Hey,  you're missing some updates from the latest update, please add them. (Check the most recent commit on en.lua to see the changes.)

**Comment by DARKAOFF** [comment]
no its here [dc31ab3](https://github.com/brezedc/lb-phone-locales/pull/38/commits/dc31ab3b768833831771d0b7f728bc564591c75a)

**Comment by DARKAOFF** [comment]
sorry @brezedc  its good

**Comment by brezedc** [comment]
You're still missing some, i'd reccommend using a website such as https://www.jsondiff.com/ to see the difference :)

**Comment by DARKAOFF** [comment]
yes I saw the problem logically it's good I corrected thx

**Comment by brezedc** [comment]
Like i said ,you're still missing some.

**Comment by DARKAOFF** [comment]
and There you go

**Comment by brezedc** [comment]
Perfect, thank you.

**Pull request merged**
